In [2]:
#EDA

In [4]:
import pandas as pd

In [4]:
! pip install pandas

Requirement already satisfied: pandas in C:\Python314\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in C:\Python314\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [22]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [6]:
print(df['Review Rating'].unique())

[3.2 3.9 3.1 4.2 3.6 3.4 nan 4.  4.3 2.8 4.8 3.8 3.3 2.5 3.  4.5 2.6 2.9
 4.1 4.6 4.7 3.5 4.9 5.  4.4 1.  2.7 2.  3.7]

In [7]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [9]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,5050.000000,5050.000000,5050,5050,5050,4494.000000,5050,4680,5050,5050,4449.000000,5050,5050,5050,4502.000000,5050,5050
unique,NaN,NaN,3,30,5,NaN,54,4,25,5,NaN,2,6,2,NaN,6,7
top,NaN,NaN,Male,Shirt,Clothing,NaN,New York,M,Black,Spring,NaN,No,Standard,No,NaN,Credit Card,Monthly
freq,NaN,NaN,3018,320,2130,NaN,337,1981,404,1280,NaN,3462,1213,2789,NaN,954,946
mean,2519.570891,44.150495,NaN,NaN,NaN,144.765236,NaN,NaN,NaN,NaN,3.668195,NaN,NaN,NaN,25.221901,NaN,NaN
std,1470.402964,15.282328,NaN,NaN,NaN,275.590101,NaN,NaN,NaN,NaN,0.865357,NaN,NaN,NaN,14.521635,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.120000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1252.250000,31.000000,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,13.000000,NaN,NaN
50%,2499.500000,44.000000,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,25.000000,NaN,NaN
75%,3740.750000,57.000000,NaN,NaN,NaN,89.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN
max,5099.000000,70.000000,NaN,NaN,NaN,1499.760000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

In [11]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

DATA CLEANING

In [12]:
df['Item Purchased']

0          T-shirt
1       Sunglasses
2            Shirt
3           Gloves
4          Jewelry
           ...
5045        Hoodie
5046      Backpack
5047         Skirt
5048      Sneakers
5049        Blouse
Name: Item Purchased, Length: 5050, dtype: object

In [14]:
df['Item Purchased'].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [16]:
df.groupby('Category')['Item Purchased'].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [18]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [21]:
correct_mapping = {
    # Clothing
    "T-shirt": "Clothing",
    "Shirt": "Clothing",
    "Shorts": "Clothing",
    "Hoodie": "Clothing",
    "Pants": "Clothing",
    "Socks": "Clothing",
    "Jeans": "Clothing",
    "Blouse": "Clothing",
    "Skirt": "Clothing",
    "Sweater": "Clothing",
    "Dress": "Clothing",

    # Accessories
    "Sunglasses": "Accessories",
    "Gloves": "Accessories",
    "Jewelry": "Accessories",
    "Hat": "Accessories",
    "Handbag": "Accessories",
    "Scarf": "Accessories",
    "Belt": "Accessories",

    # Electronics
    "Laptop": "Electronics",
    "Phone": "Electronics",
    "Watch": "Electronics",
    "Headphones": "Electronics",

    # Footwear
    "Shoes": "Footwear",
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear",
    "Jacket": "Outerwear"
}

In [22]:
correct_mapping

{'T-shirt': 'Clothing',
 'Shirt': 'Clothing',
 'Shorts': 'Clothing',
 'Hoodie': 'Clothing',
 'Pants': 'Clothing',
 'Socks': 'Clothing',
 'Jeans': 'Clothing',
 'Blouse': 'Clothing',
 'Skirt': 'Clothing',
 'Sweater': 'Clothing',
 'Dress': 'Clothing',
 'Sunglasses': 'Accessories',
 'Gloves': 'Accessories',
 'Jewelry': 'Accessories',
 'Hat': 'Accessories',
 'Handbag': 'Accessories',
 'Scarf': 'Accessories',
 'Belt': 'Accessories',
 'Laptop': 'Electronics',
 'Phone': 'Electronics',
 'Watch': 'Electronics',
 'Headphones': 'Electronics',
 'Shoes': 'Footwear',
 'Sandals': 'Footwear',
 'Sneakers': 'Footwear',
 'Boots': 'Footwear',
 'Coat': 'Outerwear',
 'Jacket': 'Outerwear'}

In [23]:
df['Category'] = df['Item Purchased'].map(correct_mapping)

In [24]:
df.groupby('Category')['Size'].unique()

Category
Accessories         [M, L, S, XL]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [25]:
df.loc[df['Category'] == 'Electronics' , 'Size'] = "Not Applicable"

In [26]:
df.groupby('Category')['Size'].unique()

Category
Accessories         [M, L, S, XL]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [28]:
df.loc[df['Category'] == 'Accessories' , 'Size'] = "Free Size"

In [29]:
df.loc[df['Category'] == 'Footwear' , 'Size'] = "Not Available"

In [31]:
mode_size = df.loc[df['Category'] == "Clothing", 'Size'].mode()[0]

df.loc[
    (df['Category'] == "Clothing") & (df['Size'].isnull()),
    'Size'
] = mode_size

In [32]:
df['Review Rating'].mean()

np.float64(3.668195100022477)

In [33]:
df['Review Rating'].median()

np.float64(3.7)

In [34]:
df['Review Rating'].mode()

0    4.0
Name: Review Rating, dtype: float64

In [35]:
df.groupby("Item Purchased")['Review Rating'].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [55]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,2,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,2,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,2,No,Store Pickup,No,17.0,Credit Card,Weekly

In [58]:
print(df['Review Rating'].unique())

[2]

In [61]:
df['Review Rating'] = pd.to_numeric(df['Review Rating'], errors='coerce')

df['Review Rating'] = df['Review Rating'].fillna(
    df.groupby('Item Purchased')['Review Rating'].transform('mean')
).round(2)

In [ ]:
correct_mapping = {
    # Clothing
    "T-shirt": "Clothing",
    "Shirt": "Clothing",
    "Shorts": "Clothing",
    "Hoodie": "Clothing",
    "Pants": "Clothing",
    "Socks": "Clothing",
    "Jeans": "Clothing",
    "Blouse": "Clothing",
    "Skirt": "Clothing",
    "Sweater": "Clothing",
    "Dress": "Clothing",

    # Accessories
    "Sunglasses": "Accessories",
    "Gloves": "Accessories",
    "Jewelry": "Accessories",
    "Hat": "Accessories",
    "Handbag": "Accessories",
    "Scarf": "Accessories",
    "Belt": "Accessories",

    # Electronics
    "Laptop": "Electronics",
    "Phone": "Electronics",
    "Watch": "Electronics",
    "Headphones": "Electronics",

    # Footwear
    "Shoes": "Footwear",
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear",
    "Jacket": "Outerwear"
}

In [62]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [63]:
df['Previous Purchases'] = df['Previous Purchases'].fillna(0)

In [65]:
df.groupby("Item Purchased")['Purchase Amount (USD)'].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [66]:
df['Purchase Amount(USD)'] = pd.to_numeric(df['Purchase Amount (USD)'], errors='coerce')

df['Purchase Amount (USD)'] = df['Purchase Amount (USD)'].fillna(
    df.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean')
).round(2)

In [67]:
df.duplicated().sum()

np.int64(50)

In [68]:
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases,Purchase Amount(USD)
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.30,No,Free Shipping,No,19.0,Cash,Monthly,56.0
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,M,Charcoal,Winter,3.10,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months,47.0
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.50,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly,75.0
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,XL,Maroon,Winter,2.90,No,Standard,No,35.0,Credit Card,Fortnightly,41.0
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,M,Orange,Winter,2.80,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly,78.0
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,M,Olive,Spring,4.60,No,Express,No,50.0,PayPal,Bi-Weekly,20.0
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.70,No,Standard,No,13.0,Venmo,Annually,89.0
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,L,Blue,Summer,3.60,No,Standard,No,33.0,Bank Transfer,Annually,77.0
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.20,No,Next Day Air,No,31.0,PayPal,Bi-Weekly,48.0
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,L,Peach,Summer,3.70,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months,67.0
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.80,No,Express,No,28.0,Cash,Fortnightly,97.0
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.80,No,Next Day Air,No,6.0,PayPal,Every 3 Months,43.0
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.70,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly,97.0
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,L,Peach,Fall,4.20,No,Free Shipping,Yes,48.0,PayPal,Annually,93.0
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.80,No,Store Pickup,No,28.0,Cash,Annually,72.0
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.90,No,Standard,No,6.0,PayPal,Weekly,89.0
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,XL,Black,Summer,3.90,No,Store Pickup,No,44.0,Venmo,Monthly,81.0
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,L,Turquoise,Winter,4.00,No,Next Day Air,No,41.0,Venmo,Fortnightly,68.0
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.20,No,Express,No,3.0,PayPal,Monthly,35.0
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,M,Red,Summer,4.50,Yes,Express,Yes,5.0,Credit Card,Quarterly,53.0
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,S,Brown,Summer,3.90,No,Express,No,40.0,Debit Card,Quarterly,92.0
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,XL,Cyan,Fall,4.60,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly,58.0
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.90,No,Store Pickup,No,15.0,Bank Transfer,Quarterly,36.0
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,L,Lavender,Summer,4.20,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months,58.0
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.50,No,Next Day Air,No,48.0,Credit Card,Every 3 Months,87.0
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,S,Red,Winter,3.81,No,2-Day Shipping,Yes,8.0,Debit Card,Annually,100.0
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.60,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly,35.0
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,S,Cyan,Winter,3.00,Yes,Standard,Yes,47.0,Credit Card,Monthly,95.0
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.40,No,Next Day Air,No,34.0,Debit Card,Annually,38.0
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,M,Lavender,Winter,4.00,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly,85.0
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.90,No,Standard,No,17.0,PayPal,Fortnightly,23.0
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.70,No,2-Day Shipping,No,12.0,Cash,Fortnightly,57.0
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.00,No,Express,No,4.0,Venmo,Fortnightly,67.0
4059,227,29,Male,Shoes,Footwear,74.0,Texas,L,Violet,Spring,3.30,Yes,Free Shipping,Yes,5.0,PayPal,Monthly,74.0
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,XL,Olive,Winter,2.70,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months,60.0
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.80,No,Free Shipping,Yes,5.0,Debit Card,Monthly,72.0
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,S,Orange,Fall,3.40,No,Free Shipping,No,2.0,Bank Transfer,Monthly,34.0
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.90,No,Standard,No,46.0,Venmo,Annually,52.0
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,XL,Magenta,Fall,3.20,No,Standard,No,47.0,Debit Card,Annually,96.0
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.90,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly,39.0
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,S,Lavender,Spring,4.60,No,Standard,Yes,14.0,Debit Card,Bi-Weekly,32.0
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.90,No,2-Day Shipping,No,46.0,Credit Card,Monthly,94.0
4595,3577,29,Female,Boots,Footwear,24.0,Maine,L,Yellow,Spring,3.00,No,Express,No,12.0,Venmo,Bi-Weekly,24.0
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,XL,Turquoise,Spring,2.90,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months,63.0
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.90,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months,89.0
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,M,Black,Fall,3.20,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly,63.0
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,M,Beige,Winter,3.00,No,Express,No,21.0,Bank Transfer,Annually,46.0
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.90,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly,54.0
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.50,No,Standard,Yes,25.0,Debit Card,Monthly,34.0
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.00,No,Store Pickup,No,33.0,Credit Card,Monthly,71.0

In [70]:
df = df.drop_duplicates(subset = ['Customer ID'] , keep='first')

In [71]:
len(df)

5000

In [23]:
df.columns = df .columns.str.replace(" " , "_")
df.columns = df.columns.str.lower()

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [21]:
print(type(df))

<class 'method'>

In [25]:
df.rename(columns={"purchase_amount_(usd)": "purchase_amount"}, inplace=True)

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [27]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

Connecting to SQL Server

In [30]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in C:\Python314\Lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in C:\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Python314\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)

In [32]:
!pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in C:\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: pyodbc in C:\Python314\Lib\site-packages (5.3.0)
Requirement already satisfied: greenlet>=1 in C:\Python314\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)

In [34]:
import sys
!{sys.executable} -m pip install sqlalchemy pyodbc

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.4.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.49-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.1 MB 2.9 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.0 MB/s eta 0:00:00
Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl (70 kB)
Downloading greenlet-3.4.0-cp313-cp313-win_amd64.whl (238 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, pyodbc, greenlet, sqlalchemy

   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ---------------------------------------- 4/4 [sqlalchemy]

Successfully installed greenlet-3.4.0 pyodbc-5.3.0 sqlalchemy-2.0.49 typing-extensions-4.15.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(
    host="localhost",        # server name
    user="root",             # username
    password="new password",# your MySQL password
    database="your_database" # your DB name
)

print("Connection successful!")

# Fetch data
df = pd.read_sql("SELECT * FROM your_table", conn)
df.head()

Connection successful!